import base64
import hashlib
import json
import struct
import tempfile
import unittest
from pathlib import Path

import numpy as np

from excited_state_diabatizer.cis_io import (
    coefficient_from_amplitudes,
    parse_cis_amplitudes,
    read_cis_header,
    validate_cis_against_output,
    write_cis_manifest,
)
from excited_state_diabatizer.models import MissingDataError


# Real 452-byte job.cis generated by ORCA 6.1.1 RELEASE with:
# ! PBE0 STO-3G TightSCF
# %tddft NRoots 2; Triplets true; TDA true; end
# and a three-atom water geometry. ORCA stored two singlet records followed by
# two restricted triplet records. Keeping the binary as base64 makes the fixture
# reviewable as a text-source edit while preserving the exact release output.
ORCA_611_RESTRICTED_TRIPLET_TDA_CIS = base64.b64decode(
    "BAAAAAEAAAAEAAAABQAAAAYAAAD/////////////////////CAAAAAAAAAABAAAAAAAA"
    "AAAAAAAAAAAAwrRgLxc43j8BAAAABQAAABQlXaZYzkq+0sFgjGmD4DwdFNOWX8nRPYDh"
    "Pa+zWzs+RGpX00vabz7qSvu3/AMEPuz//////+8/oTQP0BqIJz4IAAAAAAAAAAEAAAAA"
    "AAAAAQAAAAAAAACFFPUm93zhPwEAAAAFAAAAhlesSWHDsb9q3iCCpeJFPohmn5/XbVa+"
    "JPoykPLDwj/d0vKehpPvPziWB+kBS2U+xavltdoycL5YFv5ZDasEPggAAAAAAAAAAwAA"
    "AAAAAAABAAAAAAAAAJO2K0zSQtk/AQAAAAQAAAB3cYOodDBAPn4IDzwHwvG8gkZwNnoV"
    "yD1APRB4s1kePuR7uF2ntGq+tDs6rgFUB772///////vv6to7ZQhiQe+CAAAAAAAAAAD"
    "AAAAAAAAAAEAAAAAAAAAu55QiXrj3T8BzuEZdtXGv2suf7nAcKu/F0Qfn2gZXj4A/teh"
    "+FJfvigSGV59BbI/1rFSmt/f7784sPdSRpRovhHa36Bnc2o+XCVa0ppH8T0="
)


def _write_fixture(directory: Path, payload: bytes = ORCA_611_RESTRICTED_TRIPLET_TDA_CIS) -> Path:
    path = directory / "job.cis"
    path.write_bytes(payload)
    return path


def _minimal_restricted_rpa_fixture() -> bytes:
    payload = bytearray(
        struct.pack("<9i", 2, 0, 0, 1, 1, -1, -1, -1, -1)
    )
    for coefficient in (0.8, 0.6):
        payload.extend(struct.pack("<6i", 1, 0, 3, 0, 0, 0))
        payload.extend(struct.pack("<2d", 0.25, 0.0))
        payload.extend(struct.pack("<d", coefficient))
    return bytes(payload)


def _minimal_unrestricted_tda_fixture() -> bytes:
    payload = bytearray(
        struct.pack("<9i", 2, 1, 2, 3, 4, 0, 0, 1, 2)
    )
    for root_index, energy, coefficients in (
        (0, 0.1, (0.1, 0.2, 0.3, 0.4, 0.5, 0.6)),
        (1, 0.2, (-0.1, -0.2, -0.3, -0.4, -0.5, -0.6)),
    ):
        payload.extend(struct.pack("<6i", 6, 0, 3, 0, root_index, 0))
        payload.extend(struct.pack("<2d", energy, 0.0))
        payload.extend(struct.pack("<6d", *coefficients))
    return bytes(payload)


def _minimal_unrestricted_rpa_fixture() -> bytes:
    payload = bytearray(
        struct.pack("<9i", 2, 1, 2, 3, 4, 0, 0, 1, 2)
    )
    for coefficient in (0.8, 0.6):
        payload.extend(struct.pack("<6i", 6, 0, 3, 0, 0, 0))
        payload.extend(struct.pack("<2d", 0.25, 0.0))
        payload.extend(struct.pack("<6d", coefficient, 0.0, 0.0, 0.0, 0.0, 0.0))
    return bytes(payload)


class ORCA611CISParserTests(unittest.TestCase):
    def test_fixture_identity_and_normalized_header(self):
        self.assertEqual(len(ORCA_611_RESTRICTED_TRIPLET_TDA_CIS), 452)
        self.assertEqual(
            hashlib.sha256(ORCA_611_RESTRICTED_TRIPLET_TDA_CIS).hexdigest(),
            "18fc9621aec9ccf2fec5e95d316ca5aacadf4222aedf2fdd911cb83c3bfea56a",
        )
        with tempfile.TemporaryDirectory() as td:
            path = _write_fixture(Path(td))
            header = read_cis_header(path)

        self.assertEqual(header.layout, "orca-standard-vector-records")
        self.assertTrue(header.restricted)
        self.assertTrue(header.tda)
        self.assertEqual(header.stored_vectors, 4)
        self.assertEqual(header.nroots, 4)
        self.assertEqual(header.multiplicities, (1, 3))
        self.assertEqual(
            (
                header.alpha_occ_start,
                header.alpha_occ_end,
                header.alpha_virt_start,
                header.alpha_virt_end,
            ),
            (1, 4, 5, 6),
        )
        # The four -1 beta sentinels on disk are normalized to the alpha ranges.
        self.assertEqual(
            (
                header.beta_occ_start,
                header.beta_occ_end,
                header.beta_virt_start,
                header.beta_virt_end,
            ),
            (1, 4, 5, 6),
        )
        self.assertEqual(header.raw_ints[5:], (-1, -1, -1, -1))

    def test_global_root_mapping_and_multiplicity_filter(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write_fixture(Path(td))
            header, states = parse_cis_amplitudes(path)
            _, triplets = parse_cis_amplitudes(
                path, roots=[1, 3, 4], multiplicity=3
            )

        self.assertEqual(sorted(states), [1, 2, 3, 4])
        self.assertEqual([states[root]["multiplicity"] for root in states], [1, 1, 3, 3])
        self.assertEqual(sorted(triplets), [3, 4])
        # ORCA 6.1.1 repeats iroot=1 for both triplets in this file. The parser
        # deliberately uses vector order for the global STATE 3/STATE 4 labels.
        self.assertEqual(states[3]["orca_root_index"], 1)
        self.assertEqual(states[4]["orca_root_index"], 1)
        self.assertEqual(states[3]["root_within_multiplicity"], 1)
        self.assertEqual(states[4]["root_within_multiplicity"], 2)
        self.assertEqual(states[3]["global_root"], 3)
        self.assertEqual(states[4]["orca_gradient_iroot"], 2)
        self.assertEqual(states[3]["cis_layout"], header.layout)
        self.assertEqual(states[3]["orbital_index_base"], 0)

    def test_restricted_vector_reconstruction_and_printed_coefficients(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write_fixture(Path(td))
            header, states = parse_cis_amplitudes(path, roots=[3, 4], multiplicity=3)

        state3 = states[3]
        self.assertEqual(state3["alpha"].shape, (4, 2))
        self.assertTrue(np.allclose(state3["alpha"], state3["beta"]))
        self.assertAlmostEqual(
            float(np.sum(state3["alpha"] ** 2) + np.sum(state3["beta"] ** 2)),
            1.0,
            places=12,
        )
        self.assertAlmostEqual(
            coefficient_from_amplitudes(header, state3, 4, "a", 5, "a"),
            -1.0,
            places=12,
        )
        self.assertAlmostEqual(
            coefficient_from_amplitudes(header, states[4], 3, "a", 5, "a"),
            -0.9960783018228152,
            places=12,
        )

    def test_manifest_preserves_standard_layout_and_root_mapping_metadata(self):
        with tempfile.TemporaryDirectory() as td:
            directory = Path(td)
            cis_path = _write_fixture(directory)
            header, states = parse_cis_amplitudes(
                cis_path, roots=[3, 4], multiplicity=3
            )
            manifest = directory / "manifest.json"
            write_cis_manifest(
                manifest,
                cis_path,
                header,
                [3, 4],
                [],
                amplitudes=states,
            )
            payload = json.loads(manifest.read_text())

        self.assertEqual(payload["header"]["layout"], "orca-standard-vector-records")
        self.assertEqual(payload["header"]["multiplicities"], [1, 3])
        self.assertEqual(
            [
                (
                    state["global_root"],
                    state["multiplicity"],
                    state["orca_gradient_iroot"],
                )
                for state in payload["states"]
            ],
            [(3, 3, 1), (4, 3, 2)],
        )

    def test_real_fixture_validates_against_orca_printed_triplet_coefficients(self):
        output = """
FINAL SINGLE POINT ENERGY     -75.224282662
STATE  1:  E= 0.472173 au  12.848 eV  103630.1 cm**-1 <S**2> = 0.0 Mult 1
     4a -> 5a : 1.000000 (c= 1.00000000)
STATE  2:  E= 0.546505 au  14.871 eV  119943.9 cm**-1 <S**2> = 0.0 Mult 1
     3a -> 5a : 0.973692 (c= 0.98675853)
STATE  3:  E= 0.394703 au  10.740 eV   86627.4 cm**-1 <S**2> = 2.0 Mult 3
     4a -> 5a : 1.000000 (c= -1.00000000)
STATE  4:  E= 0.467009 au  12.708 eV  102496.7 cm**-1 <S**2> = 2.0 Mult 3
     3a -> 5a : 0.992172 (c= -0.99607830)
ORCA TERMINATED NORMALLY
"""
        with tempfile.TemporaryDirectory() as td:
            directory = Path(td)
            cis_path = _write_fixture(directory)
            out_path = directory / "job.out"
            out_path.write_text(output)
            header, states, checks = validate_cis_against_output(
                cis_path,
                out_path,
                "orca611",
                [3, 4],
            )

        self.assertEqual(header.multiplicities, (1, 3))
        self.assertEqual(sorted(states), [3, 4])
        self.assertEqual(len(checks), 2)
        self.assertTrue(all(check.passed for check in checks))

    def test_binary_output_multiplicity_disagreement_fails(self):
        output = """
STATE  1: E= 0.472173 au 12.848 eV 103630.1 cm**-1 Mult 1
STATE  3: E= 0.394703 au 10.740 eV  86627.4 cm**-1 Mult 2
"""
        with tempfile.TemporaryDirectory() as td:
            directory = Path(td)
            cis_path = _write_fixture(directory)
            out_path = directory / "job.out"
            out_path.write_text(output)
            with self.assertRaisesRegex(MissingDataError, "multiplicity 3.*multiplicity 2"):
                validate_cis_against_output(
                    cis_path,
                    out_path,
                    "orca611",
                    [1, 3],
                )

    def test_standard_non_tda_x_plus_y_pair_is_grouped_as_one_root(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write_fixture(Path(td), _minimal_restricted_rpa_fixture())
            header, states = parse_cis_amplitudes(path, tda=False)

        self.assertFalse(header.tda)
        self.assertEqual(header.stored_vectors, 2)
        self.assertEqual(header.nroots, 1)
        self.assertEqual(states[1]["response_component"], "x-plus-y")
        self.assertEqual(states[1]["x_minus_y_vector_record_index"], 1)
        self.assertAlmostEqual(
            coefficient_from_amplitudes(header, states[1], 0, "a", 1, "a"),
            0.8,
        )
        self.assertAlmostEqual(
            float(states[1]["alpha_x_minus_y"][0, 0] * np.sqrt(2.0)),
            0.6,
        )

    def test_exact_two_record_tda_non_tda_ambiguity_requires_a_hint(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write_fixture(Path(td), _minimal_restricted_rpa_fixture())
            with self.assertRaisesRegex(MissingDataError, "either one non-TDA"):
                parse_cis_amplitudes(path)
            header, states = parse_cis_amplitudes(path, tda=True)

        self.assertTrue(header.tda)
        self.assertEqual(sorted(states), [1, 2])

    def test_output_tda_status_resolves_exact_two_record_ambiguity(self):
        output = """
Tamm-Dancoff approximation     ... operative
STATE 1: E= 0.250000 au 6.803 eV 54868.7 cm**-1 Mult 3
STATE 2: E= 0.250000 au 6.803 eV 54868.7 cm**-1 Mult 3
"""
        with tempfile.TemporaryDirectory() as td:
            directory = Path(td)
            cis_path = _write_fixture(directory, _minimal_restricted_rpa_fixture())
            out_path = directory / "job.out"
            out_path.write_text(output)
            header, states, _ = validate_cis_against_output(
                cis_path,
                out_path,
                "degenerate",
                [1, 2],
            )

        self.assertTrue(header.tda)
        self.assertEqual(sorted(states), [1, 2])

    def test_standard_unrestricted_tda_records_are_not_misread_as_legacy(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write_fixture(Path(td), _minimal_unrestricted_tda_fixture())
            header, states = parse_cis_amplitudes(path)

        self.assertEqual(header.layout, "orca-standard-vector-records")
        self.assertFalse(header.restricted)
        self.assertTrue(header.tda)
        self.assertEqual(header.multiplicities, (3,))
        self.assertEqual(states[2]["root_within_multiplicity"], 2)
        self.assertAlmostEqual(
            coefficient_from_amplitudes(header, states[1], 2, "a", 4, "a"),
            0.4,
        )
        self.assertAlmostEqual(
            coefficient_from_amplitudes(header, states[1], 0, "b", 2, "b"),
            0.6,
        )

    def test_unrestricted_ambiguous_standard_file_does_not_fall_back_to_legacy(self):
        with tempfile.TemporaryDirectory() as td:
            path = _write_fixture(Path(td), _minimal_unrestricted_rpa_fixture())
            with self.assertRaisesRegex(MissingDataError, "either one non-TDA"):
                parse_cis_amplitudes(path)
            header, states = parse_cis_amplitudes(path, tda=False)

        self.assertEqual(header.layout, "orca-standard-vector-records")
        self.assertFalse(header.tda)
        self.assertEqual(sorted(states), [1])

    def test_truncated_and_bad_vector_length_files_fail_closed(self):
        bad_ncoeffs = bytearray(ORCA_611_RESTRICTED_TRIPLET_TDA_CIS)
        # Standard header is 36 bytes; the first record starts with ncoeffs.
        struct.pack_into("<i", bad_ncoeffs, 36, 7)
        payloads = [
            ORCA_611_RESTRICTED_TRIPLET_TDA_CIS[:-1],
            bytes(bad_ncoeffs),
        ]
        for payload in payloads:
            with self.subTest(size=len(payload)):
                with tempfile.TemporaryDirectory() as td:
                    path = _write_fixture(Path(td), payload)
                    with self.assertRaises(MissingDataError):
                        parse_cis_amplitudes(path)


if __name__ == "__main__":
    unittest.main()
