#!/usr/bin/env python3
"""Optimize triplet TDDFT root 4 from a restricted singlet reference.

The first calculation is an audited ORCA 6.1.1 analytic gradient at the
supplied geometry.  It reads the supplied ground-state ``.gbw`` using an
RKS-compatible C-matrix guess.  Subsequent geometries are proposed by
pysisyphus and accepted transactionally only after TDenTrack identifies a
unique continuation of the committed transition density.

The calculation uses multiplicity-local ORCA root numbering: ``--root 4``
means the fourth triplet root generated by ``triplets true``.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np

from pysisyphus.Geometry import Geometry
from pysisyphus.calculators import ORCA
from pysisyphus.calculators.ORCA6StateSurvey import (
    MULTIPLICITY_LOCAL_ROOTS,
    bootstrap_tdentrack_snapshot,
)
from pysisyphus.calculators.TDenTrackORCA import TDenTrackORCA
from pysisyphus.intcoords.PrimTypes import PrimTypes
from pysisyphus.io.xyz import geom_from_xyz
from pysisyphus.optimizers.RFOptimizer import RFOptimizer


EXPECTED_ORCA_VERSION = "6.1.1"
VALIDATION_TOLERANCE = 1.0e-6
ENERGY_TOLERANCE_EH = 5.0e-6
DEFAULT_LINEARIZED_BENDS = ((5, 0, 37),)

KEYWORDS = (
    "libxc(wb97x-d3bj) RKS def2-SVP def2/J RIJCOSX "
    "CPCM(Acetonitrile) VeryTightSCF KeepDens KeepTransDensity DEFGRID3"
)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Optimize an ORCA TDDFT triplet root from an RKS singlet "
            "reference with transactional transition-density tracking."
        )
    )
    parser.add_argument(
        "--workdir",
        type=Path,
        default=Path(os.environ.get("TDENTRACK_WORKDIR", Path.cwd())),
        help="Base directory for relative paths (default: current directory).",
    )
    parser.add_argument(
        "--xyz",
        type=Path,
        default=Path("optS0.xyz"),
        help="Initial singlet-ground-state geometry.",
    )
    parser.add_argument(
        "--gbw",
        type=Path,
        default=Path("optS0.gbw"),
        help="Ground-state orbital checkpoint used for the first RKS guess.",
    )
    parser.add_argument(
        "--initial-dir",
        type=Path,
        default=Path("initial_root4_rks_job"),
        help="Retained initial root-gradient directory.",
    )
    parser.add_argument(
        "--run-dir",
        type=Path,
        default=Path("opt_root4_rks_tdentrack"),
        help="Fresh pysisyphus optimization directory.",
    )
    parser.add_argument("--root", type=int, default=4)
    parser.add_argument("--nroots", type=int, default=15)
    parser.add_argument("--charge", type=int, default=2)
    parser.add_argument("--pal", type=int, default=14)
    parser.add_argument("--mem-per-core", type=int, default=2000)
    parser.add_argument("--max-cycles", type=int, default=50)
    parser.add_argument(
        "--coord-type",
        choices=("redund", "tric", "cart"),
        default="redund",
        help=(
            "Optimization coordinates. Standard redundant internals are the "
            "safe default for transactional trial geometries."
        ),
    )
    parser.add_argument(
        "--linearize-bend",
        nargs=3,
        type=int,
        action="append",
        metavar=("I", "J", "K"),
        help=(
            "In redundant coordinates, replace ordinary bend I-J-K with its "
            "linear-bend pair. May be repeated. Atom indices are zero-based."
        ),
    )
    parser.add_argument(
        "--tda",
        action="store_true",
        help=(
            "Use TDA instead of full TDDFT. The default intentionally matches "
            "the successful full-TDDFT RKS triplet scan."
        ),
    )
    parser.add_argument(
        "--orca",
        type=Path,
        help="Explicit ORCA executable; otherwise use ~/.pysisyphusrc or PATH.",
    )
    parser.add_argument(
        "--orca-2json",
        type=Path,
        help="Explicit orca_2json executable if it is not beside ORCA.",
    )
    parser.add_argument(
        "--preflight-only",
        action="store_true",
        help=(
            "Validate an already completed initial gradient without creating "
            "the optimization directory or launching ORCA."
        ),
    )
    return parser.parse_args(argv)


def resolve_from(workdir: Path, path: Path) -> Path:
    return (path if path.is_absolute() else workdir / path).resolve()


def build_blocks(nroots: int, *, tda: bool) -> str:
    tda_line = "  tda true\n" if tda else ""
    return f"""%basis
  NewGTO Ru "def2-TZVP" end
end

%scf
  GuessMode CMatrix
  AutoStart false
end

%tddft
  nroots {int(nroots)}
  triplets true
  irootmult triplet
  CPCMEQ true
{tda_line}  dotrans all
end"""


def build_geometry(
    xyz_path: Path,
    coord_type: str,
    linearize_bends: Iterable[Sequence[int]],
) -> Geometry:
    """Load an Å XYZ and optionally regularize selected redundant bends."""

    if coord_type != "redund":
        return geom_from_xyz(str(xyz_path), coord_type=coord_type)

    probe = geom_from_xyz(str(xyz_path), coord_type="redund")
    typed_prims = list(probe.internal.typed_prims)
    for requested in linearize_bends:
        i, j, k = map(int, requested)
        matches = [
            primitive
            for primitive in typed_prims
            if (
                primitive[0] == PrimTypes.BEND
                and primitive[2] == j
                and {primitive[1], primitive[3]} == {i, k}
            )
        ]
        if len(matches) != 1:
            raise RuntimeError(
                f"Expected exactly one ordinary bend matching {i}-{j}-{k}; "
                f"found {matches}."
            )
        ordinary = matches[0]
        typed_prims.remove(ordinary)
        indices = tuple(map(int, ordinary[1:]))
        typed_prims.extend(
            (
                (PrimTypes.LINEAR_BEND, *indices),
                (PrimTypes.LINEAR_BEND_COMPLEMENT, *indices),
            )
        )
        print(
            "Replaced near-linear redundant primitive "
            f"Bend({indices}) by a linear-bend/complement pair."
        )

    return Geometry(
        probe.atoms,
        probe.cart_coords,
        coord_type="redund",
        coord_kwargs={"typed_prims": typed_prims},
    )


def exact_engrad(path: Path) -> dict[str, object]:
    """Read the one explicitly selected ORCA EnGrad artifact."""

    values: list[str] = []
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        values.append(stripped.replace("D", "E").replace("d", "e"))
    if len(values) < 2:
        raise RuntimeError(f"Truncated EnGrad file: {path}")
    atom_count = int(values[0])
    gradients = np.asarray(
        [float(value) for value in values[2 : 2 + 3 * atom_count]],
        dtype=float,
    )
    if gradients.size != 3 * atom_count or not np.all(np.isfinite(gradients)):
        raise RuntimeError(f"Invalid gradient vector in {path}")
    return {"energy": float(values[1]), "forces": -gradients}


def find_initial_artifacts(directory: Path) -> dict[str, Path] | None:
    """Find one complete retained seed calculation, or return None if empty."""

    if not directory.exists():
        return None
    entries = list(directory.iterdir())
    if not entries:
        return None

    artifacts: dict[str, Path] = {}
    patterns = {
        "cis": "*.orca.cis",
        "bson": "*.orca.bson",
        "gbw": "*.orca.gbw",
        "out": "*.orca.out",
        "engrad": "*.orca.engrad",
    }
    for kind, pattern in patterns.items():
        matches = sorted(directory.glob(pattern))
        if len(matches) != 1:
            raise RuntimeError(
                f"Cannot safely reuse {directory}: expected one {pattern}, "
                f"found {matches}. Use a new --initial-dir or clean this "
                "directory after inspecting the failed calculation."
            )
        artifacts[kind] = matches[0]
    return artifacts


def configure_command(
    calculator: ORCA,
    *,
    orca: Path | None,
) -> None:
    if orca is not None:
        if not orca.is_file():
            raise FileNotFoundError(f"ORCA executable does not exist: {orca}")
        calculator.base_cmd = [str(orca)]


def make_orca(
    *,
    args: argparse.Namespace,
    blocks: str,
    out_dir: Path,
    base_name: str,
    gbw: Path,
) -> ORCA:
    calculator = ORCA(
        keywords=KEYWORDS,
        blocks=blocks,
        gbw=str(gbw),
        wavefunction_dump=True,
        orca_2json=(
            None if args.orca_2json is None else str(args.orca_2json.resolve())
        ),
        root=args.root,
        nroots=args.nroots,
        charge=args.charge,
        mult=1,
        pal=args.pal,
        mem=args.mem_per_core,
        out_dir=str(out_dir),
        base_name=base_name,
    )
    configure_command(calculator, orca=args.orca)
    if not calculator.triplets:
        raise RuntimeError("ORCA calculator did not recognize triplets true.")
    return calculator


def validate_initial_snapshot(
    *,
    calculator: ORCA,
    geometry: Geometry,
    roots: tuple[int, ...],
    selected_root: int,
    tda: bool,
):
    snapshot = bootstrap_tdentrack_snapshot(
        calculator=calculator,
        atoms=geometry.atoms,
        coordinates=geometry.cart_coords,
        selected_root=selected_root,
        requested_roots=roots,
        tda=tda,
        expected_orca_version=EXPECTED_ORCA_VERSION,
        validation_tolerance=VALIDATION_TOLERANCE,
    )
    numbering = snapshot.metadata.get("root_numbering")
    if numbering != MULTIPLICITY_LOCAL_ROOTS:
        raise RuntimeError(
            "Expected multiplicity-local triplet IRoot numbering, got "
            f"{numbering!r}."
        )
    wrong_multiplicities = {
        root: snapshot.multiplicities[root]
        for root in roots
        if int(snapshot.multiplicities[root]) != 3
    }
    if wrong_multiplicities:
        raise RuntimeError(
            "Restricted-reference CIS window contains non-triplet roots: "
            f"{wrong_multiplicities}."
        )
    if snapshot.selected_root != selected_root:
        raise RuntimeError(
            f"Bootstrap selected root {snapshot.selected_root}, expected "
            f"{selected_root}."
        )
    return snapshot


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.nroots < 1 or not 1 <= args.root <= args.nroots:
        raise ValueError("--root must be between 1 and --nroots.")
    if args.pal < 1 or args.mem_per_core < 1 or args.max_cycles < 1:
        raise ValueError("PAL, memory, and maximum cycles must be positive.")

    workdir = args.workdir.resolve()
    xyz_path = resolve_from(workdir, args.xyz)
    initial_gbw = resolve_from(workdir, args.gbw)
    initial_dir = resolve_from(workdir, args.initial_dir)
    run_dir = resolve_from(workdir, args.run_dir)
    args.orca = None if args.orca is None else args.orca.expanduser().resolve()
    args.orca_2json = (
        None
        if args.orca_2json is None
        else args.orca_2json.expanduser().resolve()
    )
    preflight_only = (
        args.preflight_only
        or os.environ.get("TDENTRACK_PREFLIGHT_ONLY") == "1"
    )

    for label, path in (("initial XYZ", xyz_path), ("initial GBW", initial_gbw)):
        if not path.is_file():
            raise FileNotFoundError(f"{label} does not exist: {path}")
    if args.orca_2json is not None and not args.orca_2json.is_file():
        raise FileNotFoundError(
            f"orca_2json executable does not exist: {args.orca_2json}"
        )
    if run_dir.exists() and not preflight_only:
        raise FileExistsError(
            f"Refusing to overwrite {run_dir}. Choose a new --run-dir."
        )

    linearize_bends = (
        tuple(map(tuple, args.linearize_bend))
        if args.linearize_bend is not None
        else DEFAULT_LINEARIZED_BENDS
    )
    geometry = build_geometry(xyz_path, args.coord_type, linearize_bends)
    cart_dim = geometry.cart_coords.size
    opt_dim = geometry.coords.size
    print(
        f"Geometry dimensions: Cartesian={cart_dim}, "
        f"{args.coord_type.upper()}={opt_dim}"
    )
    if opt_dim > 10 * cart_dim:
        raise RuntimeError(
            f"Implausible coordinate expansion ({opt_dim} versus {cart_dim}); "
            "check geometry units and connectivity."
        )

    blocks = build_blocks(args.nroots, tda=args.tda)
    roots = tuple(range(1, args.nroots + 1))
    artifacts = find_initial_artifacts(initial_dir)
    if preflight_only and artifacts is None:
        raise RuntimeError(
            "--preflight-only requires an already completed initial root "
            f"gradient in {initial_dir}."
        )

    seed_calc = make_orca(
        args=args,
        blocks=blocks,
        out_dir=initial_dir,
        base_name="root4_seed",
        gbw=initial_gbw,
    )
    if artifacts is None:
        print(
            f"Running initial RKS-reference triplet root-{args.root} gradient "
            f"in {initial_dir}..."
        )
        seed_calc.get_forces(geometry.atoms, geometry.cart_coords)
        artifacts = find_initial_artifacts(initial_dir)
        if artifacts is None:
            raise RuntimeError("Initial ORCA job produced no retained artifacts.")
    else:
        print(f"Reusing completed initial gradient from {initial_dir}.")
        seed_calc.cis = artifacts["cis"]
        seed_calc.bson = artifacts["bson"]
        seed_calc.gbw = artifacts["gbw"]
        seed_calc.out = artifacts["out"]

    seed_root, seed_triplets = seed_calc.parse_engrad_info(artifacts["out"])
    if seed_root != args.root or not seed_triplets:
        raise RuntimeError(
            "Initial EnGrad audit failed: output reports "
            f"root={seed_root!r}, triplets={seed_triplets}; expected local "
            f"triplet root {args.root}."
        )

    print("Bootstrapping and auditing the initial TDenTrack snapshot...")
    initial_snapshot = validate_initial_snapshot(
        calculator=seed_calc,
        geometry=geometry,
        roots=roots,
        selected_root=args.root,
        tda=args.tda,
    )
    cached_gradient = exact_engrad(artifacts["engrad"])
    raw_engrad_energy = float(cached_gradient["energy"])
    final_anchor_energy = float(
        initial_snapshot.metadata["final_single_point_energy_eh"]
    )
    if abs(raw_engrad_energy - final_anchor_energy) > ENERGY_TOLERANCE_EH:
        raise RuntimeError(
            "Initial EnGrad energy disagrees with the audited ORCA final "
            f"energy: {raw_engrad_energy:.12f} versus "
            f"{final_anchor_energy:.12f} Eh."
        )
    selected_energy = float(initial_snapshot.energies_eh[args.root])
    cached_gradient["energy"] = selected_energy

    print(f"ORCA root numbering: {MULTIPLICITY_LOCAL_ROOTS}")
    print(
        "Electronic target: restricted singlet reference, "
        f"triplet root {args.root}/{args.nroots}."
    )
    print(f"Raw cached EnGrad energy: {raw_engrad_energy:.12f} Eh")
    print(f"Selected-state energy: {selected_energy:.12f} Eh")
    print(
        "State-independent correction: "
        f"{initial_snapshot.metadata['state_independent_energy_correction_eh']:.12f} Eh"
    )

    if preflight_only:
        print("Preflight complete; no optimization directory or ORCA job was created.")
        return 0

    track_calc = TDenTrackORCA(
        initial_snapshot=initial_snapshot,
        enable_default_survey=True,
        default_survey_options={
            "requested_roots": roots,
            "expected_orca_version": EXPECTED_ORCA_VERSION,
            "validation_tolerance": VALIDATION_TOLERANCE,
            "tda": args.tda,
        },
        keywords=KEYWORDS,
        blocks=blocks,
        root=args.root,
        nroots=args.nroots,
        charge=args.charge,
        mult=1,
        pal=args.pal,
        mem=args.mem_per_core,
        out_dir=str(run_dir),
        gbw=str(initial_snapshot.artifacts["gbw"]),
        wavefunction_dump=True,
        orca_2json=(
            None if args.orca_2json is None else str(args.orca_2json)
        ),
    )
    configure_command(track_calc, orca=args.orca)
    if not track_calc.triplets:
        raise RuntimeError("Tracking calculator did not retain triplet mode.")

    geometry.set_calculator(track_calc)
    track_calc.last_orca_engrad_energy = raw_engrad_energy
    geometry.set_results(cached_gradient)
    print("Loaded the validated cycle-0 energy and gradient.")

    step_controller = {
        "type": "state_aware",
        "factors": (0.5, 0.75, 1.0, 1.25, 1.5),
        "primary_factor": 1.0,
        "fallback_only": True,
        "require_descent": True,
    }
    print(
        f"Starting root-{args.root} TDenTrack-aware optimization in {run_dir}..."
    )
    optimizer = RFOptimizer(
        geometry,
        max_cycles=args.max_cycles,
        trust_radius=0.20,
        trust_min=0.02,
        trust_max=0.50,
        dump=True,
        dump_restart=1,
        out_dir=str(run_dir),
        step_controller=step_controller,
    )
    optimizer.run()
    print("Optimization finished.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
